version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "80:80"
    environment:
      - MONGO_URI=mongodb://mongo:27017  # MongoDB URI
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.4
    container_name: mongo-db
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
